**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [1]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
# Complete the functions defined in this cell


# Test 01: Play Right
# This should print [40, 50, 60, 10, 20, 30]
def playRight(sequence, beats):
  for i in range(len(beats)):
    if beats[i]==1:
      temp=sequence[len(sequence)-1]
      for j in range(len(sequence)-1,0,-1):
        sequence[j]=sequence[j-1]
      sequence[0]=temp
    else:
      pass
  return sequence


# Test 02: Discard Cards
# This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
#[1,2,3,2,8,2,2,5,7]
def discardCards(cards, number):
    index = 0
    while index < len(cards):
        if cards[index] == number:
            cards = helper(cards, index)
        else:
            index += 1
    return cards
def helper(arr, index):
    for i in range(index, len(arr)-1):
        arr[i] = arr[i+1]
    arr[-1] = 0
    return arr


#Test 03: Merge Lineup

def mergeLineup(pokemon_1, pokemon_2):
  new_arr=np.array([0]*len(pokemon_1))
  for i in range(len(pokemon_1)):
    if pokemon_1[i]==None and pokemon_2[len(pokemon_1)-1-i]!=None:
      new_arr[i]+=0+pokemon_2[len(pokemon_2)-1-i]
    elif pokemon_1[i]!=None and pokemon_2[len(pokemon_1)-1-i]==None:
      new_arr[i]+=pokemon_1[i]+0
    elif pokemon_1[i]==None and pokemon_2[len(pokemon_1)-1-i]==None :
      new_arr[i]+=0
    else:
      new_arr[i]+=pokemon_1[i]+pokemon_2[len(pokemon_1)-1-i]
  return new_arr


# Test 04: Balance your Salami
def balanceSalami(salami):
  my_salami=0
  sibling_salami=0
  total_salami=0
  for i in range(len(salami)):
    total_salami+=salami[i]
  for i in range(len(salami)-1):
    sibling_salami+=salami[i]
    my_salami=total_salami-sibling_salami
    if sibling_salami==my_salami:
      return 'True'
  return 'False'

# Test 05: Protecc Salami
def protectSalami(salami):
  for a in range(len(salami)):
    if a<salami[a]:
      maximum=salami[a]
  protector=np.array([0]*((maximum)+1))
  count=0
  for i in range(len(protector)):
    for j in range(len(salami)):
      if i==salami[j]:
        protector[i]+=1
      if count<protector[i]:
        count+=1
  repeat_array=np.array([0]*(count+1))
  for k in range(len(repeat_array)):
    for l in range(len(protector)):
      if protector[l]>1 and k==protector[l]:
        repeat_array[k]+=1
  if repeat_array[k]==2:

      return "True"
  else:
      return "False"


# Test 05: Odd Even Wave
def waveYourFlag(arr):
  index_odd=1
  index_even=2
  new_array=np.array([0]*len(arr))
  new_array[0]=arr[0]
  for i in range(1,len(new_array)):
    if new_array[0]%2==0:
      if arr[i]%2==0:
        new_array[index_even]=arr[i]
        index_even+=2
      elif arr[i]%2!=0:
        new_array[index_odd]=arr[i]
        index_odd+=2
    else:
        if arr[i]%2==0:
          new_array[index_odd]=arr[i]
          index_odd+=2
        elif arr[i]%2!=0:
          new_array[index_even]=arr[i]
          index_even+=2
  return new_array






In [ ]:
# This cell is the driver code
# Run this cell after completion of above function.
# You will see the status Accepted after completion if your code is correct.
# If your function is wrong you will see wrong[correction percentage]
# This is called unit testing if you are wondering the checking approach
# No need to write or change any code here. You can only change the inputs

print("///  Test 01: Play Right  ///")
sequence=np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}') # This should print [40, 50, 60, 10, 20, 30]
unittest.output_test(returned_value, np.array([40, 50, 60, 10, 20, 30]))


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

pokemon_1 = np.array([4, 5, None, None])
pokemon_2 = np.array([2, None, None, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,5,0,2]
unittest.output_test(returned_value, np.array([4,5,0,2]))


print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)


print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 01: Play Right  ///
[10 10 20 30 40 50]
[60 60 10 20 30 40]
[50 50 60 10 20 30]
Task 1: [40 50 60 10 20 30]
Accepted
///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted
///  Test 03: Merge Lineup  ///
Task 3: [12  3 28 -8  5]
Accepted
Task 3: [ 4 17  6 27  2]
Accepted
Task 3: [4 5 0 2]
Accepted
///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted
///  Test 05: Protecc Salami  ///
Task 5: True
Accepted
Task 5: False
Accepted
///  Test 06: Odd Even Wave  ///
Task 6: [ 2  3 12  1  8  5]
Accepted
Task 6: [45 78 23 84 41]
Accepted
